locations_rooms = [
// 	{
// 		"id":"domenics",
// 		"name":"Domenic's",
// 		"nickname":"domenics",
// 		"coordinates": [
// 			new Point(), 
// 			],
// 		"function":"",
// 		"description":"",
// 		"category":["dining"],
// 		"entrances":[],
// 		"nearby":[],
// 	},
	{
		"id":"dd",
		"name":"Dunkin' Dounuts",
		"nickname":"DD",
		"coordinates": [
			new Point(42.363174, -71.260435), 
			new Point(42.363149, -71.260429), 
			new Point(42.363118, -71.260645), 
			new Point(42.363148, -71.260623), 
			],
		"function":"",
		"description": "",
		"category":["dining"],
		"entrances":[],
		"nearby":[],
	},
	{
		"id":"einstein",
		"name":"Einstein Bros. Bagels",
		"nickname":"Einstein",
		"coordinates": [
			new Point(42.365729, -71.260335), 
			new Point(42.365671, -71.260347), 
			new Point(42.365669, -71.260454), 
			new Point(42.365729, -71.260444), 
			],
		"function":"",
		"description":"",
		"category":["dining"],
		"entrances":[],
		"nearby":[],
	},
// 	{
// 		"id":"facultyclub",
// 		"name":"Faculty Club",
// 		"nickname":"faculty club",
// 		"coordinates": [
// 			new Point(), 
// 			],
// 		"function":"",
// 		"description":"",
// 		"category":["dining"],
// 		"entrances":[],
// 		"nearby":[],
// 	},
	{
		"id":"shermandining",
		"name":"Sherman Dining Hall",
		"nickname":"Sherman",
		"coordinates": [
			new Point(42.366622, -71.260961), 
			new Point(42.366687, -71.260819), 
			new Point(42.366599, -71.260734), 
			new Point(42.366681, -71.260543), 
			new Point(42.366559, -71.260432), 
			new Point(42.366437, -71.260811), 
			],
		"function":"",
		"description":"Sherman Dining Hall is one of main dining facilities on campus. It is an all-you-care-to- eat buffet style option. Sherman is unique in that it is the only integrated kosher (Jewish dietary law) cafeteria in the country, where all students can eat together in the same place. Options include grilled foods, a sandwich station, a salad bar, pizza, a stir fry bar, omelet stations, a gluten free section, a crepe station, vegan and vegetarian options, as well as a large dessert selection. Furthermore, students can submit recipes from home and receive notice as to when these coveted meals will be served in Sherman.",
		"category":["dining"],
		"entrances":[],
		"nearby":[],
	},
// 		{
// 		"id":"starbucksHeller",
// 		"name":"Heller Starbucks",
// 		"nickname":"heller startbucks",
// 		"coordinates": [
// 			new Point(), 
// 			],
// 		"function":"",
// 		"description":"",
// 		"category":["dining"],
// 		"entrances":[],
// 		"nearby":[],
// 	},
		{
		"id":"starbucksLib",
		"name":"Library Starbucks",
		"nickname":"Library starbucks",
		"coordinates": [
			new Point(42.367862, -71.258553), 
			new Point(42.367839, -71.258619), 
			new Point(42.367822, -71.258622), 
			new Point(42.367852, -71.258542), 
			],
		"function":"",
		"description":"",
		"category":["dining"],
		"entrances":[],
		"nearby":[],
	},
		{
		"id":"peets",
		"name":"Peet's Coffe & Tea",
		"nickname":"Peet's",
		"coordinates": [
			new Point(42.366049, -71.257998),
			new Point(42.365951, -71.258019),  
			new Point(42.366002, -71.258139), 
			new Point(42.366077, -71.258103), 
			],
		"function":"",
		"description":"",
		"category":["dining"],
		"entrances":[],
		"nearby":[],
	},
		{
		"id":"stein",
		"name":"The Stein Restaurant",
		"nickname":"Stein",
		"coordinates": [
			new Point(42.366529, -71.260891), 
			new Point(42.366637, -71.260648), 
			new Point(42.366551, -71.260574), 
			new Point(42.366435, -71.260811), 
			],
		"function":"",
		"description":"",
		"category":["dining"],
		"entrances":[],
		"nearby":[],
	},
// 	{
// 		"id":"usdanBoulevard",
// 		"name":"Usdan Boulevard",
// 		"nickname":"boulevard",
// 		"coordinates": [
// 			new Point(), 
// 			],
// 		"function":"",
// 		"description":"",
// 		"category":["dining"],
// 		"entrances":[],
// 		"nearby":[],
// 	},
// 	{
// 		"id":"usdanCafe",
// 		"name":"Usdan Dining Hall",
// 		"nickname":"usdan",
// 		"coordinates": [
// 			new Point(), 
// 			],
// 		"function":"",
// 		"description":"",
// 		"category":["dining"],
// 		"entrances":[],
// 		"nearby":[],
// 	},	
//{
// 		"id":"cStore",
// 		"name":"HOOT Market",
// 		"nickname":"c store",
// 		"coordinates": [
// 			new Point(), 
// 			],
// 		"function":"",
// 		"description":"",
// 		"category":["dining"],
// 		"entrances":[],
// 		"nearby":[],
// 	},
// {
// 		"id":"usdanLouisDeli",
// 		"name":"Usdan Louis' Deli",
// 		"nickname":["deli","louis"],
// 		"coordinates": [
// 			new Point(), 
// 			],
// 		"function":"",
// 		"description":"",
// 		"category":["dining"],
// 		"entrances":[],
// 		"nearby":[],
//  },
// 	{
// 		"id":"isso",
// 		"name":"International Students and Scholars Office",
// 		"nickname":"isso",
// 		"coordinates": [
// 			new Point(), 
// 			],
// 		"function":"",
// 		"description":"",
// 		"category":["administrative"],
// 		"entrances":[],
// 		"nearby":[],
// 	},
// 	{
// 		"id":"mail",
// 		"name":"Mail Room",
// 		"nickname":"mail",
// 		"coordinates": [
// 			new Point(), 
// 			],
// 		"function":"",
// 		"description":"",
// 		"category":["administrative"],
// 		"entrances":[],
// 		"nearby":[],
// 	},
// 	{
// 		"id":"registrar",
// 		"name":"Registrar Office",
// 		"nickname":"registrar",
// 		"coordinates": [
// 			new Point(), 
// 			],
// 		"function":"",
// 		"description":"",
// 		"category":["administrative"],
// 		"entrances":[],
// 		"nearby":[],
// 	},
	{
		"id":"bookStore",
		"name":"Book Store",
		"nickname":"Book store",
		"coordinates": [
			new Point(42.365738, -71.260542), 
			new Point(42.365735, -71.260419),
			new Point(42.365535, -71.260426),
			new Point(42.365508, -71.260579),
			],
		"function":"",
		"description":"",
		"category":[],
		"entrances":[],
		"nearby":[],
	},
]

function Point(x,y) {
	this.x = x;
	this.y = y;
}
